<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
 xmlns:tei="http://www.tei-c.org/ns/1.0" xmlns:dctl="http://www.ctl.sns.it/ns/1.0"
 xmlns:exslt="http://exslt.org/common" xmlns:dyn="http://exslt.org/dynamic"
 xmlns:str="http://exslt.org/strings" xmlns:php="http://php.net/xsl">
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:output method="html" indent="yes" encoding="UTF-8" omit-xml-declaration="no" />
 <xsl:strip-space elements="*" />
 <!-- * * * * * * * * * * * * * * * * -->
 <!-- * COMMON * -->
 <!-- * * * * * * * * * * * * * * * * -->
 <!-- - - - - - - - - - - - - - - - -->
 <!-- GET ID -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template name="get_id">
 <xsl:choose>
  <xsl:when test="not(@xml:id)">
  <xsl:value-of select="generate-id(.)" />
  </xsl:when>
  <xsl:otherwise>
  <xsl:value-of select="@xml:id" />
  </xsl:otherwise>
 </xsl:choose>
 </xsl:template>
 <!-- * * * * * * * * * * * * * * * * -->
 <!-- * INITIALIZE * -->
 <!-- * * * * * * * * * * * * * * * * -->
 <!-- - - - - - - - - - - - - - - - -->
 <!-- ROOT -->
 <xsl:template match="tei:TEI">
 <html>
  <xsl:comment> HTML generated from XML master. Do not edit this file! </xsl:comment>
  <head>
  <link href="../../_common/checker/dctl-checker.css" type="text/css" rel="stylesheet" />
  <title>
   <xsl:value-of select="tei:teiHeader/tei:fileDesc/tei:titleStmt/tei:author" />
   <xsl:text xml:space="preserve">, </xsl:text>
   <xsl:value-of select="tei:teiHeader/tei:fileDesc/tei:titleStmt/tei:title[@type='main']" />
   <xsl:text xml:space="preserve"> - </xsl:text>
   <xsl:value-of select="tei:teiHeader/tei:fileDesc/tei:publicationStmt/tei:date" />
   <xsl:text xml:space="preserve"> </xsl:text>
   <xsl:value-of select="tei:teiHeader/tei:fileDesc/tei:publicationStmt/tei:publisher" />
  </title>
  </head>
  <body>
  <div class="col_container">
   <div class="col_left">
   <a id="_header" />
   <xsl:apply-templates select="tei:teiHeader" />
   <a id="toc" />
   <xsl:call-template name="toc" />
   </div>
   <div class="col_right">
   <a id="text" />
   <xsl:apply-templates select="//tei:text" />
   </div>
  </div>
  </body>
 </html>
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- TEI HEADER -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template match="tei:teiHeader">
 <div class="chk_boxText">
  <span class="chk_boxTitle">TEI Header - Document</span>
  <!-- Use a table so we can align data correctly -->
  <div>
  <span class="chk_labelH">ID</span>
  <span class="chk_valueH">
   <xsl:value-of select="parent::node()/@xml:id" />
  </span>
  <br />
  <span class="chk_labelH">Access type</span>
  <span class="chk_valueH">
   <xsl:variable name="access_type" select="tei:fileDesc/tei:publicationStmt/tei:availability/@n" />
   <xsl:choose>
   <xsl:when test="access_type=1">Search + Display</xsl:when>
   <xsl:when test="access_type=2">Display</xsl:when>
   <xsl:otherwise>Browse + Search + Display</xsl:otherwise>
   </xsl:choose>
  </span>
  <br />
  <span class="chk_labelH">Title</span>
  <span class="chk_valueH">
   <xsl:value-of select="tei:fileDesc/tei:titleStmt/tei:title[@type='main']" />
  </span>
  <br />
  <span class="chk_labelH">Author</span>
  <span class="chk_valueH">
   <xsl:value-of select="tei:fileDesc/tei:titleStmt/tei:author" />
  </span>
  <br />
  <span class="chk_labelH">Last update</span>
  <span class="chk_valueH">
   <xsl:value-of select="tei:fileDesc/tei:publicationStmt/tei:date" />
  </span>
  <br />
  <span class="chk_labelH">Source</span>
  <span class="chk_valueH">
   <xsl:value-of select="tei:fileDesc/tei:sourceDesc/tei:biblFull/tei:titleStmt/tei:author" />
   <xsl:text>, "</xsl:text>
   <xsl:value-of
   select="tei:fileDesc/tei:sourceDesc/tei:biblFull/tei:titleStmt/tei:title[@type='main']" />
   <xsl:text>" (</xsl:text>
   <xsl:value-of select="tei:fileDesc/tei:sourceDesc/tei:biblFull/tei:publicationStmt/tei:date" />
   <xsl:text>, </xsl:text>
   <xsl:value-of select="//tei:text/@xml:lang" />
   <xsl:text>)</xsl:text>
  </span>
  <br />
  </div>
 </div>
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- FRONT -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template match="tei:front | tei:body | tei:back">
 <div class="chk_boxText">
  <span class="chk_label" title="{name()}.{@type}.{@n}">[<xsl:value-of select="local-name()" />]</span>
  <xsl:apply-templates />
 </div>
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- TEXT -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template match="tei:text">
 <xsl:apply-templates />
 </xsl:template>
 <!-- * * * * * * * * * * * * * * * * -->
 <!-- * PALETTE * -->
 <!-- * * * * * * * * * * * * * * * * -->
 <!-- - - - - - - - - - - - - - - - -->
 <!-- PALETTE -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template name="palette">
 <div class="chk_palette">
  <xsl:text> [ </xsl:text>
  <a href="#header" class="chk_palette" title="teiHeader">teiHeader</a>
  <xsl:text> | </xsl:text>
  <a href="#toc" class="chk_palette" title="ToC">ToC</a>
  <xsl:text> | </xsl:text>
  <a href="#text" class="chk_palette" title="Text">Text</a>
  <xsl:text> ] </xsl:text>
 </div>
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- PALETTE TOC -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template name="palette_toc">
 <div class="chk_palette">
  <xsl:text> [ </xsl:text>
  <a href="#div" class="chk_palette" title="teiHeader">div</a>
  <xsl:text> | </xsl:text>
  <a href="#index" class="chk_palette" title="ToC">index</a>
  <xsl:text> | </xsl:text>
  <a href="#id" class="chk_palette" title="ToC">xml:id</a>
  <xsl:text> | </xsl:text>
  <a href="#ref" class="chk_palette" title="Text">ref</a>
  <xsl:text> | </xsl:text>
  <a href="#figure" class="chk_palette" title="Text">figure</a>
  <xsl:text> | </xsl:text>
  <a href="#name" class="chk_palette" title="Text">name</a>
  <xsl:text> | </xsl:text>
  <a href="#table" class="chk_palette" title="Text">table</a>
  <xsl:text> | </xsl:text>
  <a href="#list" class="chk_palette" title="Text">list</a>
  <xsl:text> ] </xsl:text>
 </div>
 </xsl:template>
 <!-- * * * * * * * * * * * * * * * * -->
 <!-- * TOC * -->
 <!-- * * * * * * * * * * * * * * * * -->
 <!-- - - - - - - - - - - - - - - - -->
 <!-- TOC -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template name="toc">
 <div class="chk_boxText">
  <span class="chk_divHead"> ToC </span>
  <br />
  <xsl:call-template name="palette_toc" />
  <div id="div">
  <span class="chk_headTitle">div</span>
  <xsl:call-template name="toc_div" />
  </div>
  <xsl:call-template name="palette_toc" />
  <div id="index">
  <span class="chk_headTitle">index</span>
  <xsl:call-template name="toc_index" />
  </div>
  <xsl:call-template name="palette_toc" />
  <div id="id">
  <span class="chk_headTitle">xml:id</span>
  <xsl:call-template name="toc_id" />
  </div>
  <xsl:call-template name="palette_toc" />
  <div id="ref">
  <span class="chk_headTitle">ref</span>
  <xsl:call-template name="toc_ref" />
  </div>
  <xsl:call-template name="palette_toc" />
  <div id="figure">
  <span class="chk_headTitle">figure</span>
  <xsl:call-template name="toc_figure" />
  </div>
  <xsl:call-template name="palette_toc" />
  <div id="name">
  <span class="chk_headTitle">name</span>
  <xsl:call-template name="toc_name" />
  </div>
  <xsl:call-template name="palette_toc" />
  <div id="table">
  <span class="chk_headTitle">table</span>
  <xsl:call-template name="toc_table" />
  </div>
  <xsl:call-template name="palette_toc" />
  <div id="list">
  <span class="chk_headTitle">list</span>
  <xsl:call-template name="toc_list" />
  </div>
  <xsl:call-template name="palette_toc" />
 </div>
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- TOC :: NAME -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template name="toc_name">
 <table border="1" cellpadding="2" cellspacing="0">
  <tr>
  <th class="chk_label">proper/generic</th>
  <th class="chk_label">key?type</th>
  </tr>
  <xsl:for-each select="tei:text//tei:name | tei:text//tei:rs">
  <xsl:sort select="." />
  <xsl:variable name="thisID">
   <xsl:call-template name="get_id" />
  </xsl:variable>
  <tr>
   <td class="chk_small">
   <a href="#{$thisID}" title="jump to...">
    <xsl:value-of select="." />
   </a>
   </td>
   <td class="chk_small">
   <a href="#{$thisID}" title="jump to...">
    <xsl:value-of select="@key | @type" />
   </a>
   </td>
  </tr>
  </xsl:for-each>
 </table>
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- TOC :: TABLE -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template name="toc_table">
 <table border="1" cellpadding="2" cellspacing="0">
  <tr>
  <th class="chk_label">type</th>
  <th class="chk_label">head</th>
  </tr>
  <xsl:for-each select="tei:text//tei:table">
  <xsl:variable name="thisID">
   <xsl:call-template name="get_id" />
  </xsl:variable>
  <tr>
   <td class="chk_small">
   <a href="#{$thisID}" title="jump to...">
    <xsl:value-of select="name()" />
   </a>
   </td>
   <td>
   <a href="#{$thisID}" title="jump to...">
    <xsl:value-of select="substring(tei:head[1],1,25)" />
   </a>
   </td>
  </tr>
  </xsl:for-each>
 </table>
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- TOC :: LIST -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template name="toc_list">
 <table border="1" cellpadding="2" cellspacing="0">
  <tr>
  <th class="chk_label">type</th>
  <th class="chk_label">head</th>
  </tr>
  <xsl:for-each select="tei:text//tei:list">
  <xsl:variable name="thisID">
   <xsl:call-template name="get_id" />
  </xsl:variable>
  <tr>
   <td class="chk_small">
   <a href="#{$thisID}" title="jump to...">
    <xsl:value-of select="name()" />
   </a>
   </td>
   <td>
   <a href="#{$thisID}" title="jump to...">
    <xsl:value-of select="substring(tei:head[1],1,25)" />
   </a>
   </td>
  </tr>
  </xsl:for-each>
 </table>
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- TOC :: FIGURE -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template name="toc_figure">
 <table border="1" cellpadding="2" cellspacing="0">
  <tr>
  <th class="chk_label">desc</th>
  <th class="chk_label">graphic</th>
  </tr>
  <xsl:for-each select="tei:text//tei:figure">
  <xsl:variable name="thisID">
   <xsl:call-template name="get_id" />
  </xsl:variable>
  <tr>
   <td class="chk_small">
   <a href="#{$thisID}" title="jump to...">
    <xsl:value-of select="tei:figDesc" />
   </a>
   </td>
   <td class="chk_small">
   <a href="#{$thisID}" title="jump to...">
    <xsl:value-of select="tei:graphic/@url" />
   </a>
   </td>
  </tr>
  </xsl:for-each>
 </table>
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- TOC :: DIV -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template name="toc_div">
 <table border="1" cellpadding="2" cellspacing="0">
  <tr>
  <th class="chk_label">type</th>
  <th class="chk_label">n</th>
  <th class="chk_label">content</th>
  </tr>
  <xsl:for-each select="tei:text//tei:div">
  <xsl:variable name="thisID">
   <xsl:call-template name="get_id" />
  </xsl:variable>
  <tr>
   <td class="chk_small">
   <a href="#{$thisID}" title="jump to...">
    <xsl:value-of select="@type" />
   </a>
   </td>
   <td class="chk_small">
   <a href="#{$thisID}" title="jump to...">
    <xsl:value-of select="@n" />
   </a>
   </td>
   <td class="chk_small">
   <xsl:variable name="aVar">
    <xsl:choose>
    <xsl:when test="tei:head!=''">
     <xsl:value-of select="substring(tei:head[1],1,25)" />
    </xsl:when>
    <xsl:otherwise>
     <xsl:value-of select="substring(.,1,25)" />
    </xsl:otherwise>
    </xsl:choose>
   </xsl:variable>
   <a href="#{$thisID}" title="jump to...">
    <xsl:value-of select="normalize-space($aVar)" />
   </a>
   <br />
   </td>
  </tr>
  </xsl:for-each>
 </table>
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- TOC :: INDEX -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template name="toc_index">
 <table border="1" cellpadding="2" cellspacing="0">
  <tr>
  <th class="chk_label">index</th>
  <th class="chk_label">refers to</th>
  </tr>
  <xsl:for-each select="tei:text//tei:index/tei:term">
  <xsl:variable name="thisID">
   <xsl:call-template name="get_id" />
  </xsl:variable>
  <tr>
   <td class="chk_small">
   <a href="#{$thisID}" title="jump to...">
    <xsl:value-of select="." />
   </a>
   </td>
   <td class="chk_small">
   <a href="#{$thisID}" title="jump to...">
    <xsl:variable name="block" select="ancestor::tei:div[1]" />
    <xsl:text>&lt;div type="</xsl:text>
    <xsl:value-of select="$block/@type" />
    <xsl:text>"</xsl:text>
    <xsl:text> n="</xsl:text>
    <xsl:value-of select="$block/@n" />
    <xsl:text>"&gt;</xsl:text>
   </a>
   </td>
  </tr>
  </xsl:for-each>
 </table>
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- TOC :: ID -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template name="toc_id">
 <table border="1" cellpadding="2" cellspacing="0">
  <tr>
  <th class="chk_label">id</th>
  <th class="chk_label">content</th>
  </tr>
  <xsl:for-each select="tei:text//tei:*[@xml:id]">
  <xsl:variable name="thisID">
   <xsl:call-template name="get_id" />
  </xsl:variable>
  <tr>
   <td class="chk_small">
   <a href="#{$thisID}" title="jump to...">
    <xsl:value-of select="@xml:id" />
   </a>
   </td>
   <td class="chk_small">
   <xsl:variable name="aVar">
    <xsl:value-of select="substring(.,1,25)" />
   </xsl:variable>
   <a href="#{$thisID}" title="jump to...">
    <xsl:value-of select="$aVar" />
   </a>
   <br />
   </td>
  </tr>
  </xsl:for-each>
 </table>
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- TOC :: REF -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template name="toc_ref">
 <table border="1" cellpadding="2" cellspacing="0">
  <tr>
  <th class="chk_label">context</th>
  <th class="chk_label">n</th>
  <th class="chk_label">target</th>
  </tr>
  <xsl:for-each select="tei:text//tei:*[@target]">
  <xsl:variable name="thisID">
   <xsl:call-template name="get_id" />
  </xsl:variable>
  <tr>
   <td class="chk_small">
   <xsl:variable name="aVar">
    <xsl:value-of select="substring(.,1,25)" />
   </xsl:variable>
   <a href="#{$thisID}" title="jump to...">
    <xsl:value-of select="$aVar" />
   </a>
   <br />
   </td>
   <td class="chk_small">
   <a href="#{$thisID}" title="jump to...">
    <xsl:value-of select="@n" />
   </a>
   </td>
   <td class="chk_small">
   <a href="#{$thisID}" title="jump to...">
    <xsl:value-of select="str:tokenize(@target)" />
   </a>
   </td>
  </tr>
  </xsl:for-each>
 </table>
 </xsl:template>
 <!-- * * * * * * * * * * * * * * * * -->
 <!-- * TEI * -->
 <!-- * * * * * * * * * * * * * * * * -->
 <!-- - - - - - - - - - - - - - - - -->
 <!-- AUTHOR -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template match="tei:author">
 <xsl:if test=".!=''">
  <span class="chk_author" title="{name()}">, <xsl:apply-templates />
  </span>
 </xsl:if>
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- BIBL -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template match="tei:bibl">
 <xsl:apply-templates />
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- CELL -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template match="tei:cell">
 <td>
  <xsl:apply-templates />
 </td>
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- DATE -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template match="tei:date">
 <span class="chk_date" title="{name()}: {@value}">
  <xsl:apply-templates />
 </span>
 </xsl:template>
<!-- - - - - - - - - - - - - - - - -->
 <!-- DATE -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template match="tei:distributor">
  <xsl:apply-templates />
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- DIV -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template match="tei:div">
 <xsl:variable name="thisID">
  <xsl:call-template name="get_id" />
 </xsl:variable>
 <div class="chk_boxText" title="{name()}.{@type}.{@n}">
  <xsl:attribute name="id">
  <xsl:value-of select="$thisID" />
  </xsl:attribute>
  <span class="chk_label" title="{name()}.{@type}.{@n}">[<xsl:value-of select="@type" />
  <xsl:if test="@n!=''">
   <xsl:text> n.</xsl:text>
   <xsl:value-of select="@n" />
  </xsl:if>]</span>
  <xsl:apply-templates />
 </div>
 <br />
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- FIGDESC -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template match="tei:figDesc">
 <span class="chk_label" title="{name()}">[desc] <xsl:apply-templates />
 </span>
 <br />
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- FIGURE -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template match="tei:figure">
 <xsl:variable name="thisID">
  <xsl:call-template name="get_id" />
 </xsl:variable>
 <span class="chk_label" title="Iconclass: {@iconclass}">
  <xsl:attribute name="id">
  <xsl:value-of select="$thisID" />
  </xsl:attribute>[ic] <xsl:value-of select="@iconclass" />
 </span>
 <br />
 <xsl:apply-templates />
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- FOREIGN -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template match="tei:foreign">
 <xsl:if test=".!=''">
  <span class="chk_foreign" title="{name()} : {@xml:lang}">
  <xsl:apply-templates />
  </span>
 </xsl:if>
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- GRAPHIC -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template match="tei:graphic">
 <xsl:variable name="thisID">
  <xsl:call-template name="get_id" />
 </xsl:variable>
 <xsl:variable name="true_url" select="substring-after(@url,'img://')" />
 <img class="img" src="_thumbs/{@true_url}" alt="({@url})" name="{tei:graphic/@url}"
  title="{$thisID} : {@url}">
  <xsl:attribute name="id">
  <xsl:value-of select="$thisID" />
  </xsl:attribute>
 </img>
 <xsl:apply-templates />
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- ITEM -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template match="tei:item">
 <li>
  <xsl:apply-templates />
 </li>
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- HEAD -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template match="tei:head">
 <xsl:if test=".!=''">
  <br />
  <span class="chk_divHead" title="{name()} : {@type}">
  <xsl:apply-templates />
  </span>
 </xsl:if>
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- INDEX -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template match="tei:index">
 <xsl:apply-templates />
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- LB -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template match="tei:lb">
 <span class="chk_label" title="{name()}">&#172;</span>
 <xsl:if test="@n">
  <span class="chk_label">
  <xsl:value-of select="@n" />
  <xsl:text>&#160;</xsl:text>
  </span>
 </xsl:if>
 <br />
 <xsl:apply-templates />
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- LIST -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template match="tei:list">
 <xsl:choose>
  <xsl:when test="@type='bulleted'">
  <ul type="disc" title="{name()}.{@xml:id}">
   <xsl:apply-templates />
  </ul>
  </xsl:when>
  <xsl:when test="@type='ordered'">
  <ol>
   <xsl:apply-templates />
  </ol>
  </xsl:when>
  <xsl:otherwise>
  <ul type="circle">
   <xsl:apply-templates />
  </ul>
  </xsl:otherwise>
 </xsl:choose>
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- MILESTONE UNIT="WB" -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template match="tei:milestone[@unit='wb']">
 <span class="chk_label" title="milestone unit='wb'">
  <xsl:text>/</xsl:text>
 </span>
 <xsl:apply-templates />
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- NAME -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template match="tei:name">
 <xsl:variable name="thisID">
  <xsl:call-template name="get_id" />
 </xsl:variable>
 <span class="chk_name" id="{$thisID}" title="{name()} : {@key}">
  <xsl:apply-templates />
 </span>
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- NOTE -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template match="tei:note">
 <span class="chk_note" title="{name()}">
  <xsl:apply-templates />
 </span>
 </xsl:template>
<!-- - - - - - - - - - - - - - - - -->
 <!-- P -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template match="tei:p">
 <p class="chk_p">
  <xsl:apply-templates />
 </p>
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- PB -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template match="tei:pb">
 <div class="chk_page">
  <xsl:text>p.</xsl:text>
  <xsl:value-of select="@n" />
  <xsl:if test="@ed">
  <xsl:text> (</xsl:text>
  <xsl:value-of select="@ed" />
  <xsl:text>)</xsl:text>
  </xsl:if>
  <xsl:text>&#160;</xsl:text>
 </div>
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- PUBLICATIONSTMT -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template match="tei:publicationStmt">
 <xsl:apply-templates />
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- PUBLISHER -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template match="tei:publisher">
 <xsl:text>, </xsl:text>
 <xsl:apply-templates />
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- PUBPLACE -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template match="tei:pubPlace">
 <xsl:text>, </xsl:text>
 <xsl:apply-templates />
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- Q -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template match="tei:q">
 <span class="chk_q" title="{name()}">
  <xsl:apply-templates />
 </span>
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- REF -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template match="tei:ref">
 <xsl:variable name="thisID">
  <xsl:call-template name="get_id" />
 </xsl:variable>
 <span class="chk_ref" id="{$thisID}" title="{name()} : {@n} @ {@target}">
  <xsl:apply-templates />
 </span>
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- ROW -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template match="tei:row">
 <tr>
  <xsl:apply-templates />
 </tr>
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- RS -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template match="tei:rs">
 <xsl:variable name="thisID">
  <xsl:call-template name="get_id" />
 </xsl:variable>
 <span class="chk_rs" id="{$thisID}" title="{name()} : {@type}">
  <xsl:apply-templates />
 </span>
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- SEG -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template match="tei:seg">
 <span class="chk_seg" title="{name()}.{@xml:id}">
  <xsl:apply-templates />
 </span>
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- TABLE -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template match="tei:table">
 <table title="{name()}.{@xml:id}" border="1">
  <xsl:apply-templates />
 </table>
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- TERM -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template match="tei:term">
 <xsl:if test=".!=''">
  <span class="chk_index" title="{name()}">
  <span class="chk_label" title="index">[idx] </span>
  <xsl:apply-templates />
  </span>
 </xsl:if>
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- TITLE -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template match="tei:title">
 <xsl:if test=".!=''">
  <span class="chk_title" title="{name()}"> &quot;<xsl:apply-templates />&quot; </span>
 </xsl:if>
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- TITLESTMT -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template match="tei:titleStmt">
 <xsl:apply-templates />
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- DCTL:* -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template match="dctl:*">
 <span class="chk_block" title="dctl:*">
 <span class="chk_label" title="{@type}">[<xsl:choose>
   <xsl:when test="@n !=''">"<xsl:value-of select="@n" />"</xsl:when>
   <xsl:otherwise>
   <xsl:value-of select="name()" />
   </xsl:otherwise>
  </xsl:choose>] </span>
  <xsl:apply-templates />
  </span>
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- DCTL:STUDIO -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template match="dctl:studio">
 <span class="chk_studio" title="{name()}">
  <xsl:apply-templates />
 </span>
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- DCTL:TRANSCRIPTION -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template match="dctl:transcription">
  <xsl:apply-templates />
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
 <!-- ANY OTHER -->
 <!-- - - - - - - - - - - - - - - - -->
 <xsl:template match="*">
 <div class="chk_error">
  <xsl:text> ? </xsl:text>
  <xsl:value-of select="name()" />
  <xsl:text> ? </xsl:text>
 </div>
 <xsl:apply-templates />
 </xsl:template>
 <!-- - - - - - - - - - - - - - - - -->
</xsl:stylesheet>
